---
- hosts: mikrotik
  gather_facts: no
  serial: 4

  roles:
    - ping #shell
    - ssh_check #shell
    - api_enable #paramiko
    - socks_disable #paramiko
    - snmp_enable #paramiko
    - change_password #api
    #- backup #paramiko
