---
- name: enable snmp
  connection: paramiko
  raw: /snmp set enabled=yes; /snmp community set public addresses="10.0.0.0/8"; quit
  register: result
  ignore_errors: yes
  when:
    - ansible_host != ""
    - ssh
  changed_when: false
